### ISSUE TITLE
Boostrap SASS Variables

### ISSUE THREAD

**Issue by ghost** [braginteractive/StrapPress#1]
Hello,
I need help including built-in custom variables file **[_variables.scss](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss)**. I am kinda lost with your SASS mapping.

```
// Bootstrap overrides
//
// Copy variables from `_variables.scss` to this file to override default values
// without modifying source files.

$body-bg:    $gray-dark;
$body-color: $gray-light;
```

**Comment by braginteractive** [comment]
What do you need help with? Copy any of the Bootstrap variables into the sass/vars/_vars.scss file and you can override the Bootstrap variables.

**Comment by ghost** [comment]
I tried that but didn`t work

**Comment by braginteractive** [comment]
What variable are you trying to override?

**Comment by ghost** [comment]
I tried changing page background color, but didn`t change.

`$body-bg:  #000;`

**Comment by braginteractive** [comment]
This should help: https://www.youtube.com/watch?v=Ohkn0YeC5gE

**Comment by ghost** [comment]
Your video posted method requires importing every SASS mixins variable one by one. There should be less hard method.
You may try to work through the variable that change pagination background, by default your method won`t make it work as well.

`$pager-bg:     $pagination-bg !default;`

**Comment by braginteractive** [comment]
Not really, you just need to set the colors you want to use.

Then you can do:
`$pager-bg: $color;`

or better yet:

`$pagination-bg: $color;`

which will change the pagination-bg color and the pager-bg color..
