### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by carpebenny** [braginteractive/StrapPress#2]
Hi. I'm not sure if this is the right place to contact you at, but I am getting the following javascript error while using StrapPress.

Uncaught TypeError: Cannot read property 'fn' of undefined
    at o (scripts.min.js?ver= :1)
    at scripts.min.js?ver= :1
    at scripts.min.js?ver= :1
    at scripts.min.js?ver= :3

<img width="654" alt="screen shot 2018-01-03 at 3 48 26 pm" src="https://user-images.githubusercontent.com/31454614/34544847-9fa17248-f09d-11e7-9eac-873a48571e71.png">
<img width="1090" alt="screen shot 2018-01-03 at 3 48 34 pm" src="https://user-images.githubusercontent.com/31454614/34544848-9fb66108-f09d-11e7-865f-8bbb25aa5b2a.png">
<img width="1167" alt="screen shot 2018-01-03 at 3 48 44 pm" src="https://user-images.githubusercontent.com/31454614/34544849-9fcd33ec-f09d-11e7-927f-e57c903b6758.png">
<img width="966" alt="screen shot 2018-01-03 at 3 48 52 pm" src="https://user-images.githubusercontent.com/31454614/34544850-9fe650f2-f09d-11e7-98f8-40fc7547c9d0.png">

**Comment by braginteractive** [comment]
Are you using the latest version of StrapPress? It was recently update to Bootstrap beta 3.

Do you have any other WordPress plugin installed?

**Comment by carpebenny** [comment]
I downloaded on 12/15. Did you change to Bootstrap beta 3 after that?

Only plugin I have installed is Advanced Custom Fields.

**Comment by braginteractive** [comment]
Check out the commit history: [https://github.com/braginteractive/StrapPress/commits/master](https://github.com/braginteractive/StrapPress/commits/master)

The theme was updated 5 days ago.

**Comment by carpebenny** [comment]
So this update replaces Bootstrap 4 to beta 3? Do I just replace the updated files? Sorry for the questions, just want to be as accurate as possible to avoid any mistakes.

**Comment by carpebenny** [comment]
And thanks for setting up this theme. It's awesome and saved me tons of time.

**Comment by braginteractive** [comment]
The update is to Bootstrap 4 beta3 from Bootstrap 4 beta2. 

Yes, you can also replace the updated files if you prefer to do it that way. 

You can also run `npm update` from the root directory of the theme files to update the theme if you are using node/npm. Or you can download the latest theme files.

**Comment by carpebenny** [comment]
Thanks for all your help!
