### ISSUE TITLE
[SUGGESTION] - Tag Releases + Add to WPackagist

### ISSUE THREAD

**Issue by wkhayrattee** [braginteractive/StrapPress#3]
Hi @braginteractive , first of all thank yo so much for putting the energy and drive to bring forward Strapress. I really appreciate. On behalf of all users, I THANK YOU for all you do.

My suggestions: 
1) Please tag releases (using semver). This will help us users to keep track of things.

2) If possible, add a composer file specifying `"type": "wordpress-theme"` and add to wpackagist.org

For the 2nd one, I will try to make a PR soon.

3) Probably add strapress on it own namespace so that it is something like `StrapPress/StrapPress`

**Comment by braginteractive** [comment]
Thanks for the suggestions. Look forward to the PRs
