### ISSUE TITLE
missing sidebar call

### ISSUE THREAD

**Issue by chrismccoy** [braginteractive/StrapPress#6]
templates are missing the get_sidebar() call, has the registered sidebar, wasnt sure if the theme was actually going to use it.

**Comment by braginteractive** [comment]
This is on purpose. I am starting to roll out changes to the theme in favor of Gutenberg. With Gutenberg, you can build the pages/posts to look however you want including sidebars. 

If you need/want the StrapPress version before these major changes, you can down the pre-gutenberg version here: https://github.com/braginteractive/StrapPress/releases
